logging:
  level:
    com.example.demo: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


# prior to spring boot 2.x this is the liquibase configuration
liquibase:
  change-log: classpath:db/changelog/changelog-master.yml

# starting with spring boot 2.x this is the liquibase configuration
spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

  h2:
    # H2 console is visible under http://localhost:8080/h2
    console:
      enabled: true
      path: /h2

management:
  security:
    enabled: false
  # enable detailed view under http://localhost:8080/actuator/health
  endpoint:
    health:
      show-details: always

https:
  enabled: false