---
platform: linux
image_resource:
  type: docker-image
  source: {repository: concourse/buildroot, tag: curl}

inputs:
  - name: version
  - name: build
  - name: source-code
outputs:
  - name: release-candidate

run:
  path: source-code/ci/scripts/promote-build.sh
