---
resources:
- name: source-code-resource
  type: git
  source:
    uri: {{source-code-resource-uri}}
    branch: {{source-code-resource-branch}}

jobs:
- name: job-build-and-verify
  plan:
  - get: source-code-resource
    trigger: true
  - task: build-and-verify
    file: source-code-resource/ci/tasks/maven-build.yml
    input_mapping: {source-code: source-code-resource}
    params:
     M2_SETTINGS_REPO_ID : {{m2-settings-repo-id}}
     M2_SETTINGS_REPO_USERNAME : {{m2-settings-repo-username}}
     M2_SETTINGS_REPO_PASSWORD : {{m2-settings-repo-password}}
     M2_SETTINGS_REPO_RELEASE_URI : {{m2-settings-repo-release-uri}}
     M2_SETTINGS_REPO_SNAPSHOT_URI : {{m2-settings-repo-snapshot-uri}}
